# Loki configuration
server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  chunk_target_size: 1048576
  max_chunk_age: 1h
  max_retention: 7d

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks

chunk_store_config:
  max_look_back_period: 0s

limits_config:
  max_query_length: 1h
  max_query_series: 500000

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h
