server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml  # Ensures log position tracking

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s  # Ensure logs are fetched frequently
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
    pipeline_stages:
      - json:
          expressions:
            observed_timestamp_rfc3339: observed_timestamp_rfc3339
            instrumentation_scope: instrumentation_scope
            severity_text: severity_text
      - timestamp:
          source: observed_timestamp_rfc3339
          format: RFC3339
      - labels:
          instrumentation_scope:
          severity_text:
