apiVersion: v1
kind: Service
metadata:
  name: loki-service
spec:
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: loki
---
apiVersion: v1
kind: Service
metadata:
  name: promtail-service
spec:
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: promtail
